name    'shanemadden-redis_multinode'
version '0.1.0'
source 'git://github.com/shanemadden/shanemadden-redis_multinode.git'
author 'shanemadden'
license 'Apache License, Version 2.0'
summary 'Puppet module for building a multi-node Redis failover group with Sentinel'
description 'Puppet module for building a multi-node Redis failover group with Sentinel'
project_page 'https://github.com/shanemadden/shanemadden-redis_multinode'

dependency 'puppetlabs/vcsrepo', '>= 0.2.0'
